---
- hosts: "{{ host }}"
  gather_facts: yes

  tasks:

    - name: Add software-properties-common package
      apt:
        pkg: software-properties-common
        state: latest
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_release != 'focal'

    - name: Add PPA repositories
      apt_repository:
        repo: "{{ item.repo }}"
      with_items:
        - { repo: "ppa:certbot/certbot" }
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_release != 'focal'

    - name: Update dist
      apt: 
        update_cache: yes

    - name: Install Certbot
      apt: 
        pkg: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - python3-certbot-nginx

    - name: Create & set chmod USER:USER to /var/www/{{ domain }}/html
      file: 
        state: directory
        path: "{{ item.path }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644
      with_items:
        - { path: "/var/www" }
        - { path: "/var/www/{{ domain }}/html" }

    - name: Add {{ domain }}.conf to /etc/nginx/sites-available
      template:
        src: ./templates/http-domain.j2
        dest: /etc/nginx/sites-available/{{ domain }}.conf

    - name: Create symbolic link for {{ domain }}.conf to /etc/nginx/sites-enabled
      file:
        state: link
        src: /etc/nginx/sites-available/{{ domain }}.conf
        dest: /etc/nginx/sites-enabled/{{ domain }}.conf
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644
      notify:
        - restart_nginx

  handlers:
  
    - name: restart_nginx
      service:
        name: nginx
        state: restarted
