---
- hosts: "{{ host }}"
  become: true

  tasks:

    - name: Add PPA repositories
      apt_repository:
        repo: "{{ item.repo }}"
      with_items:
        - { repo: "ppa:certbot/certbot" }
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_release != 'focal'

    - name: Install Certbot
      apt: 
        pkg: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - certbot
        - python3-certbot-nginx

    - name: Create /var/www/{{ domain }}/html folder, set chown USER:USER
      file: 
        state: directory
        path: /var/www/{{ domain }}/html
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0700

    - name: Add HTTP version of {{ domain }}.conf to /etc/nginx/sites-available
      template:
        src: ./templates/http-domain.j2
        dest: /etc/nginx/sites-available/{{ domain }}.conf

    - name: Create symbolic link for HTTP version of {{ domain }}.conf to /etc/nginx/sites-enabled
      file:
        state: link
        src: /etc/nginx/sites-available/{{ domain }}.conf
        dest: /etc/nginx/sites-enabled/{{ domain }}.conf
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0700
      notify:
        - reload_nginx

    - name: Dry run before create SSL certificate for {{ domain }}
      command: 
        cmd: certbot --nginx certonly --agree-tos -m {{ email }} -d {{ domain }} -d www.{{ domain }} --dry-run

    - name: Create SSL certificate for {{ domain }}
      command: 
        cmd: certbot --nginx certonly --agree-tos -m {{ email }} -d {{ domain }} -d www.{{ domain }}

    - name: Add HTTPS version of {{ domain }}.conf to /etc/nginx/sites-available
      template:
        src: ./templates/https-domain.j2
        dest: /etc/nginx/sites-available/{{ domain }}.conf
      notify:
        - reload_nginx

  handlers:
  
    - name: reload_nginx
      service:
        name: nginx
        state: reloaded
